import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { useLocation } from 'react-router-dom';
import { getSiteSettings, SiteSettings } from './api';
import { useAuth } from './auth';

type Locale = 'zh-CN' | 'en-US';
type TranslationKey = keyof typeof translations['zh-CN'];

type SiteContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
  siteSettings: SiteSettings | null;
  refreshSiteSettings: () => Promise<void>;
  announcementOpen: boolean;
  openAnnouncement: () => void;
  closeAnnouncement: () => void;
};

const LOCALE_STORAGE_KEY = 'aethergenix_locale';
const ANNOUNCEMENT_SEEN_KEY = 'aethergenix_announcement_seen_at';

const translations = {
  'zh-CN': {
    top_history: '历史记录',
    top_more: '我的',
    top_register: '注册',
    top_owner: '当前身份',
    top_credits: '可用余额',
    top_logout: '退出登录',
    top_login: '登录',
    top_announcement: '公告',
    top_tasks: '任务',
    top_favorites: '收藏',
    bottom_create: '创作',
    bottom_history: '历史',
    bottom_favorites: '收藏',
    bottom_me: '我的',
    mobile_menu_open: '打开菜单',
    mobile_menu_close: '关闭菜单',
    side_title: '导航',
    side_create: '创作',
    side_history: '生成历史',
    side_ecommerce: '电商',
    side_favorites: '我的收藏',
    side_account: '账户',
    side_config: '设置',
    account_center_area: 'AetherGenix 账户',
    account_center_title: '我的',
    account_center_desc: '查看当前登录状态和可用余额。',
    account_center_overview: '账户',
    account_center_settings: '设置',
    side_generate: '开始生成',
    home_scan: '系统扫描',
    home_title: '灵感图库',
    explore_desc: '发现 AI 生成的精彩作品，点击图片复用提示词直接创作',
    home_owner: '当前身份 {value}',
    home_guest: '游客 {value}',
    home_clone_prompt: '复用提示词',
    home_favorite_case: '收藏案例',
    home_unfavorite_case: '取消收藏',
    home_favorite_saved: '已收藏案例',
    home_favorite_removed: '已取消收藏',
    home_favorite_login_required: '请先登录后再收藏案例',
    home_generation_login_required: '请先注册或登录后再生成图片',
    home_prompt_copied: '提示词已填入并复制到剪贴板',
    home_mode: '模式',
    home_mode_edit: '改图',
    home_mode_generate: '生图',
    home_panel_expand: '展开生成面板',
    home_panel_collapse: '收起生成面板',
    home_tab_general: '灵感生成',
    home_tab_ecommerce: '电商详情页',
    home_ecom_product_image: '商品图',
    home_ecom_product_name: '商品名称',
    home_ecom_materials: '材质/用料',
    home_ecom_selling_points: '核心卖点',
    home_ecom_scenarios: '使用场景',
    home_ecom_platform: '目标平台',
    home_ecom_style: '视觉风格',
    home_ecom_extra: '额外要求',
    home_ecom_upload_tip: '上传商品主图',
    home_ecom_missing_image: '请先上传商品图',
    home_ecom_sent: '电商详情页任务已发送',
    home_ecom_image_ready: '商品主图已载入',
    home_ecom_image_removed: '商品主图已删除',
    ecom_reset_form: '重置表单',
    ecom_form_reset: '电商表单已重置',
    ecom_tag: '电商工作台',
    ecom_title: '电商详情页设计',
    ecom_subtitle: '上传商品主图，生成成套详情页，并按项目继续编辑单张成品。',
    ecom_projects: '设计项目',
    ecom_empty: '暂时还没有电商设计项目。',
    ecom_open_project: '查看项目',
    ecom_project_detail: '项目详情',
    ecom_back_projects: '返回项目',
    ecom_reference_image: '参考图',
    ecom_no_reference: '无参考图',
    ecom_screen_index: '第 {value} 张',
    ecom_edit_this_image: '编辑此图',
    ecom_edit_references: '编辑参考图',
    ecom_edit_reference_tip: '默认会使用原商品主图和当前成品图。可额外拖入参考图，只补充风格、场景或局部细节。',
    ecom_add_reference: '添加参考',
    ecom_form_restored: '已带出该项目的提交参数',
    ecom_publish_material: 'AI 发布文案',
    ecom_publish_hint: '根据该项目商品主题、卖点和场景独立生成，适合小红书、朋友圈或运营素材库。',
    ecom_publish_title: '标题',
    ecom_publish_body: '正文',
    ecom_generate_publish: '生成发布文案',
    ecom_regenerate_publish: '重新生成文案',
    ecom_publish_empty: '点击生成后，AI 会根据当前项目参数生成独立标题和正文。',
    ecom_publish_generated: '发布文案已生成',
    ecom_copy_title: '复制标题',
    ecom_copy_body: '复制正文',
    ecom_copy_all: '复制全部',
    ecom_publish_copied: '发布文案已复制',
    ecom_generation_login_required: '请先注册或登录后再生成电商详情页',
    ecom_ai_designer: 'AI 商品设计师',
    ecom_ai_designer_hint: '用户只上传商品也可以先分析商品特征、卖点、场景和适合的设计方案，再一键套用到生成表单。',
    ecom_analyze_product: 'AI 分析商品',
    ecom_analyzing: '分析中',
    ecom_analysis_ready: '商品分析已完成',
    ecom_analysis_empty: '上传商品图后点击分析，AI 会识别商品特征并推荐 3 套可直接生成的方案。',
    ecom_analysis_summary: '商品识别结果',
    ecom_analysis_type: '商品类型',
    ecom_analysis_appearance: '外观特征',
    ecom_analysis_material: '可见材质',
    ecom_analysis_constraints: '一致性约束',
    ecom_apply_plan: '套用此方案',
    ecom_plan_applied: '已套用推荐方案',
    home_message_edit_sent: '改图请求已发送',
    home_message_generate_sent: '生图请求已发送',
    home_message_queued: '任务已提交，正在排队',
    home_message_processing: '任务执行中，请稍候',
    home_message_saved: '结果已存入历史',
    home_message_waiting: '等待输入',
    home_message_loaded: '已载入配置',
    home_placeholder: '在这里输入你的生成提示词...',
    home_ref_image: '参考图',
    reference_role: '用途',
    reference_note: '备注',
    reference_note_placeholder: '说明这张图主要参考什么',
    reference_role_subject: '主体/主图',
    reference_role_front: '正面',
    reference_role_side: '侧面',
    reference_role_back: '背面',
    reference_role_material: '材质细节',
    reference_role_color: '颜色参考',
    reference_role_structure: '结构款式',
    reference_role_scene: '场景参考',
    reference_role_style: '风格参考',
    reference_role_layout: '排版参考',
    reference_role_other: '其他',
    home_execute: '执行',
    home_edit: '改图',
    home_generate: '生成',
    home_optimize_prompt: 'AI 优化',
    home_optimizing_prompt: '优化中',
    home_prompt_instruction: '修改要求：例如主角改成白色家用机器人，保留原构图',
    home_prompt_optimized: '提示词已优化',
    home_prompt_optimizer_empty: '请先输入提示词',
    home_ref_image_invalid: '请拖入 PNG、JPG 或 WebP 图片',
    home_size: '清晰度',
    home_size_fast: '快速',
    home_aspect_ratio: '比例',
    home_quality: '质量',
    home_image_count: '张数',
    create_workspace_tag: '创作工作台',
    create_workspace_title: '把想法整理成一次可执行的生成任务',
    create_workspace_desc: '写下主体、场景、风格和用途；需要保留商品、材质或构图时，把参考图拖进输入区。',
    create_active_tasks: '{count} 个任务运行中',
    create_task_center_idle: '任务中心空闲',
    create_mode_general_title: '图像生成',
    create_mode_general_sub: '全能图像模型',
    create_mode_ecommerce_title: '电商图',
    create_mode_ecommerce_sub: '商品场景图',
    create_task_input_title: '任务输入',
    create_reference_flow: '已添加 {count} 张参考图，当前会走改图/参考生成流程。',
    create_text_flow: '未添加参考图，当前会走纯文本生成流程。',
    create_remove_reference: '删除参考图',
    create_reference_role_label: '参考图用途',
    create_reference_note_label: '参考图备注',
    create_reference_note_placeholder: '例如：参考材质',
    create_reference_upload_title: '拖入或上传参考图',
    create_reference_upload_desc: '商品主图、材质细节、风格参考都可以，最多 8 张。',
    create_add_reference: '添加参考图',
    create_prompt_placeholder_general: '描述主体、环境、构图、光线和风格，如：玻璃温室里的机械花，清晨自然光，细腻材质...',
    create_prompt_placeholder_ecommerce: '描述商品、卖点和目标场景，如：白色运动鞋，干净棚拍背景，突出鞋底纹理和轻盈运动感...',
    create_prompt_required: '请输入提示词',
    create_prompt_before_optimize: '请先输入提示词',
    create_generate_image: '生成图片',
    create_example_general_1: '一张未来感城市夜景海报，雨后街道反射霓虹，电影级光影，16:9',
    create_example_general_2: '玻璃温室里的白色机械花，清晨自然光，细腻材质，干净构图',
    create_example_general_3: '复古科幻杂志封面，一艘橙色探测飞船穿过土星环，颗粒胶片质感',
    create_example_ecommerce_1: '黑色智能手表，放在岩石和冷光水面上，突出金属边框和运动防水感',
    create_example_ecommerce_2: '白色运动鞋，干净棚拍背景，轻微悬浮，强调鞋底纹理和透气网面',
    create_example_ecommerce_3: '护肤精华瓶，暖色浴室台面，水珠和柔和晨光，高级电商主图',
    create_workflow_general_1: '输入场景和风格',
    create_workflow_general_2: '可选参考图',
    create_workflow_general_3: '生成后进入工作台继续编辑',
    create_workflow_ecommerce_1: '上传商品或风格参考',
    create_workflow_ecommerce_2: '描述卖点与使用场景',
    create_workflow_ecommerce_3: '输出更适合主图和场景图',
    create_output_title: '输出预期',
    create_output_reference_mode: '参考生成',
    create_output_text_mode: '文本生成',
    create_output_size: '尺寸',
    create_output_count_value: '{count} 张',
    create_output_desc: '提交成功后会进入独立工作台，可查看结果、继续编辑，并从历史记录回到该任务。',
    create_recent_tasks_title: '最近任务',
    create_view_all_tasks: '查看全部',
    create_recent_tasks_empty: '还没有任务。生成后，这里会显示最近的进行中和已完成任务。',
    create_task_status_queued: '排队中',
    create_task_status_running: '执行中',
    create_task_status_succeeded: '已完成',
    create_task_status_failed: '失败',
    home_loading_feed: '案例加载中...',
    home_loading_more: '正在加载更多案例...',
    home_load_more: '加载更多案例',
    home_all_loaded: '案例已全部加载',
    home_empty_feed: '暂时还没有可展示的案例。',
    home_case_search: '搜索案例标题、提示词或作者',
    home_case_search_keyword: '关键词',
    home_case_search_ai: 'AI 搜索',
    home_case_ai_searching: 'AI 搜索中',
    home_case_ai_query: 'AI 已提炼：{value}',
    home_case_clear_search: '清空搜索',
    home_case_total: '案例 {total} 条',
    home_case_search_results: '搜索结果 {total} 条',
    home_back_to_top: '回到顶部',
    history_tag: '历史',
    history_title: '历史记录',
    history_subtitle: '查看并管理此前生成的图像记录。',
    history_search: '搜索提示词...',
    history_apply_filter: '应用历史筛选',
    history_failed: '生成失败',
    history_download: '下载',
    history_download_zip: '打包下载',
    history_delete: '删除',
    history_preview: '预览',
    history_regenerate: '重新生成',
    history_publish_case: '公开到案例',
    history_unpublish_case: '取消公开',
    history_published: '已公开',
    history_load_more: '加载更多',
    history_loading: '正在同步历史记录',
    history_empty_title: '还没有生成记录',
    history_empty_desc: '从创作页提交第一张图后，结果会自动沉淀到这里。',
    history_search_empty_title: '没有匹配的历史记录',
    history_search_empty_desc: '换一个提示词关键词，或清空搜索查看全部历史。',
    history_login_title: '登录后查看历史',
    history_login_desc: '登录后可以同步生成记录、继续编辑作品并重新生成。',
    history_error_title: '历史记录加载失败',
    history_error_desc: '网络或上游服务暂时没有返回数据，请稍后重试。',
    history_clear_search: '清空搜索',
    history_create_action: '去创作',
    history_retry: '重试',
    favorites_tag: '收藏案例',
    favorites_title: '我的收藏',
    favorites_subtitle: '查看你收藏过的公开案例，快速复用提示词。',
    favorites_search: '搜索收藏案例...',
    favorites_search_action: '搜索',
    favorites_loading: '收藏加载中...',
    favorites_empty: '暂时还没有收藏案例。',
    favorites_empty_title: '还没有收藏案例',
    favorites_empty_desc: '在灵感图库里收藏喜欢的案例，它们会集中出现在这里。',
    favorites_search_empty_title: '没有匹配的收藏',
    favorites_search_empty_desc: '试试更短的关键词，或清空搜索返回全部收藏。',
    favorites_error_title: '收藏加载失败',
    favorites_error_desc: '收藏列表暂时不可用，请重试。',
    favorites_all_loaded: '收藏已全部加载',
    favorites_login_required: '收藏功能仅对登录用户开放。',
    favorites_login_title: '登录后管理收藏',
    favorites_login_desc: '收藏会绑定到你的 AetherGenix 账户，登录后可跨设备同步。',
    favorites_explore_action: '去探索',
    account_tag: '账户',
    account_title: '账户',
    account_identity: '身份信息',
    account_owner: '身份',
    account_registered: '注册用户',
    account_guest: '游客会话',
    account_user: '显示名称',
    account_sub2api_username: 'AetherGenix 用户名',
    account_email: '邮箱',
    account_model: '模型',
    account_api_key: '额度访问方式',
    account_api_managed: '账户自动绑定',
    account_api_override: '账户额度',
    account_api_manual: '游客额度',
    account_api_missing: '未配置',
    account_balance: '可用余额',
    account_history: '历史数',
    account_succeeded: '{value} 次成功',
    account_edits: '改图数',
    account_last: '最近：{value}',
    account_sync_hint: '登录后可同步余额和生成记录',
    account_balance_synced: '可用余额已同步',
    account_balance_syncing: '可用余额同步中，请稍后刷新',
    account_balance_pending: '可用余额暂未同步，请稍后刷新',
    account_recent_generation: '最近生成',
    account_area_title: '我的账户',
    account_current_identity: '当前身份',
    account_logged_in_identity: '已登录 AetherGenix 账户',
    account_guest_identity: '访客体验中',
    account_balance_unsynced: '暂未同步',
    account_generation_records: '生成记录',
    account_generation_record_value: '{total} 次生成，{edits} 次编辑',
    account_refresh: '刷新账户',
    account_sync_error_desc: '账户信息暂时没有同步成功，余额和充值状态稍后刷新即可恢复显示。',
    account_recharge_action: '打开充值页面',
    account_login_or_register: '登录/注册',
    recharge_tag: '充值',
    recharge_title: '可用余额',
    recharge_desc: '充值完成后回到这里刷新余额。',
    recharge_open_external: '打开充值页面',
    recharge_open_external_note: '将在新页面打开。充值完成后回到这里刷新余额。',
    recharge_iframe_hint: '充值完成后，回到 AetherGenix 刷新余额即可继续生成。',
    recharge_login_required: '登录后查看余额',
    recharge_login_desc: '登录后可以查看当前余额，并打开充值页面。',
    recharge_loading: '充值通道加载中',
    recharge_current_balance: '当前余额',
    recharge_refresh: '刷新余额',
    recharge_refreshing: '刷新中',
    recharge_external_desc: '当前余额会自动同步。需要补充余额时，打开充值页面完成操作。',
    recharge_external_missing: '充值入口暂不可用，请联系站主。',
    recharge_balance_syncing: '正在同步余额',
    recharge_balance_updated: '余额已更新',
    recharge_balance_pending: '余额暂未同步',
    recharge_balance_sync_failed: '余额暂时无法同步',
    recharge_balance_retry: '重试',
    config_profile: '用户资料',
    config_mode: '模式',
    config_mode_user: 'AetherGenix 用户',
    config_mode_guest: '游客',
    config_balance: '余额：{value}',
    config_guest_tip: '当前是游客体验。登录或注册后，可以同步账户余额和创作记录。',
    config_sign_in: '登录',
    config_register: '注册',
    config_title: '设置',
    config_session_user: '账号会话',
    config_session_guest: '游客会话',
    config_user_desc: '当前配置绑定到已登录的 AetherGenix 账户。系统会自动使用账户额度，必要时也可以切换为备用访问密钥。',
    config_guest_desc: '游客模式按浏览器 Cookie 隔离数据，只适合临时试用。登录后可同步账户额度和创作历史。',
    config_cases: '案例库',
    config_cases_summary: '已同步 {total} 条案例 · 最近 {time}',
    config_cases_sources: '{value} 个案例源',
    config_sync_cases: '同步案例',
    config_save_case_sources: '保存案例源',
    config_user_name: '用户名',
    config_model: '模型',
    config_size: '尺寸',
    config_quality: '质量',
    config_api_key: '备用访问密钥',
    config_saved_key: '已保存密钥：{value}',
    config_key_managed: '自动绑定',
    config_key_override: '手动覆盖',
    config_key_manual: '手动',
    config_restore_key: '恢复自动绑定密钥',
    config_test: '测试连接',
    config_save: '保存配置',
    config_usage_log: '用量日志',
    config_usage_log_empty: '暂无用量日志',
    config_usage_actual: '实际扣费',
    config_usage_estimated: '本地估算',
    config_status_saved: '配置已保存',
    config_status_connected: '连接正常：{value}',
    config_status_synced: '已同步 {value} 条案例',
    config_status_restored: '已恢复自动绑定密钥',
    config_status_site_saved: '站点设置已保存',
    config_site_title: '界面与公告',
    config_site_desc: '语言选择会保存在当前浏览器。管理员保存后，会更新站点默认语言与公告内容。',
    config_default_user_name: 'AetherGenix User',
    config_account_settings: '账户设置',
    config_guest_tip_plain: '当前是游客体验。登录或注册后，可以同步账户余额和创作记录。',
    config_user_desc_plain: '你已登录 AetherGenix，余额和创作记录会随账户同步。',
    config_guest_desc_plain: '游客数据只保存在当前浏览器。登录后可以跨设备同步余额和历史记录。',
    config_account_profile: '账户资料',
    config_display_name: '显示名称',
    config_email: '邮箱',
    config_email_after_login: '登录后显示',
    config_account_status: '账户状态',
    config_status_signed_in: '已登录，正在同步账户数据',
    config_status_guest: '游客体验，仅保存在当前浏览器',
    config_balance_status: '余额状态',
    config_balance_status_desc: '生成图片时会自动使用你的账户余额。需要充值时前往统一充值入口即可。',
    config_usage_summary: '使用摘要',
    config_usage_total: '创作次数',
    config_usage_succeeded: '成功生成',
    config_usage_last: '最近创作',
    config_site_desc_user: '选择你偏好的界面语言。站点公告更新后会自动提醒，也可以在这里重新查看。',
    config_announcement_pref: '公告提醒',
    config_announcement_disabled: '当前没有启用公告',
    config_announcement_empty_enabled: '站点公告已开启，内容更新时会自动提醒你。',
    config_announcement_placeholder: '有新的站点通知时，这里会显示公告入口。',
    config_view_announcement: '查看公告',
    login_access: '访问入口',
    login_title: '登录',
    login_title_2fa: '二次验证',
    login_desc: '使用你的 AetherGenix 账户登录。登录后会自动同步你的额度和生成记录。',
    login_desc_2fa: '请输入 {value} 的 6 位验证码。',
    login_email: '邮箱',
    login_password: '密码',
    login_totp: 'TOTP 验证码',
    login_submit: '登录',
    login_submit_2fa: '验证 2FA',
    login_new: '还没有账号？',
    register_access: '注册入口',
    register_title: '创建账户',
    register_desc: '创建 AetherGenix 账户后，即可使用同一份额度生成图片，并同步生成历史。',
    register_disabled: '当前暂未开放新账户注册。',
    register_email: '邮箱',
    register_password: '密码',
    register_verify_code: '验证码',
    register_send_code: '发送验证码',
    register_promo: '优惠码',
    register_invitation: '邀请码',
    register_submit: '注册',
    register_exists: '已经注册？',
    lang_label: '界面语言',
    lang_zh: '中文',
    lang_en: 'English',
    site_announcement: '站点公告',
    site_announcement_enabled: '启用公告弹窗',
    site_announcement_title: '公告标题',
    site_announcement_body: '公告内容',
    site_upstream: 'Sub2API 集成',
    site_upstream_hint: '留空则使用环境变量。修改后全站生图、注册登录、余额和用量明细都会走新的 Sub2API 实例。',
    site_provider_base_url: 'Sub2API /v1 代理地址',
    site_auth_base_url: 'Sub2API 认证管理地址',
    site_recharge_url: 'Sub2API 充值页地址',
    site_upstream_effective: '当前生效：{value}',
    site_admin_token: 'Sub2API 管理员 Admin API Key',
    site_admin_jwt: 'Sub2API 管理员 JWT',
    site_admin_token_hint: '用于新用户注册送余额。留空表示不修改当前保存值；需要更换时粘贴新值后保存。',
    site_admin_token_saved: '当前：{value}',
    site_trial_balance_usd: '新用户赠送余额',
    site_trial_balance_effective: '当前赠送：${value}',
    site_inspiration_sources: '案例源',
    site_inspiration_sources_body: '案例源地址，一行一个。支持 GitHub 仓库地址或 raw README 地址。',
    site_announcement_save: '保存公告',
    site_settings_save: '保存站点设置',
    site_admin_only: '仅管理员可编辑站点设置。',
    announcement_empty: '当前没有公告内容。',
    modal_close: '关闭',
    modal_preview: '图片预览',
    modal_open_image: '打开原图',
    modal_download: '下载',
    modal_previous: '上一张',
    modal_next: '下一张',
    image_load_failed: '图片加载失败',
    image_retry: '重新加载',
    prompt_editor_title: '提示词编辑器',
    prompt_editor_expand: '展开编辑',
    prompt_editor_collapse: '收起',
    prompt_editor_copy: '复制',
    prompt_editor_clear: '清空',
    tasks_title: '任务中心',
    tasks_subtitle: '提交后的生图和改图任务会在这里继续执行。',
    tasks_empty: '当前还没有任务。',
    tasks_empty_title: '还没有后台任务',
    tasks_empty_desc: '从创作页提交生成或改图后，进度会显示在这里。',
    tasks_filter_empty_title: '当前筛选没有任务',
    tasks_filter_empty_desc: '切回全部任务，或开始一次新的创作。',
    tasks_clear_filter: '查看全部',
    tasks_create_action: '去创作',
    tasks_open_history: '查看历史',
    tasks_active: '{value} 个运行中',
    tasks_idle: '空闲',
    tasks_filter_all: '全部',
    tasks_filter_active: '运行中',
    tasks_filter_succeeded: '已完成',
    tasks_filter_failed: '失败',
    tasks_status_queued: '排队中',
    tasks_status_running: '执行中',
    tasks_status_succeeded: '已完成',
    tasks_status_failed: '失败',
    tasks_toast_succeeded: '任务完成',
    tasks_toast_failed: '任务失败',
    toast_success: '操作成功',
    toast_error: '操作失败',
    toast_info: '提示',
  },
  'en-US': {
    top_history: 'History',
    top_more: 'Me',
    top_register: 'Register',
    top_owner: 'Owner',
    top_credits: 'Available Credits',
    top_logout: 'Logout',
    top_login: 'Login',
    top_announcement: 'Announcement',
    top_tasks: 'Tasks',
    top_favorites: 'Favorites',
    bottom_create: 'Create',
    bottom_history: 'History',
    bottom_favorites: 'Favorites',
    bottom_me: 'Me',
    mobile_menu_open: 'Open menu',
    mobile_menu_close: 'Close menu',
    side_title: 'Navigation',
    side_create: 'Create',
    side_history: 'Generation History',
    side_ecommerce: 'E-commerce',
    side_favorites: 'Favorites',
    side_account: 'Account',
    side_config: 'Settings',
    account_center_area: 'AetherGenix Account',
    account_center_title: 'Me',
    account_center_desc: 'Check your sign-in state and available credits.',
    account_center_overview: 'Account',
    account_center_settings: 'Settings',
    side_generate: 'Generate New',
    home_scan: 'System Scan',
    home_title: 'Inspiration Feed',
    explore_desc: 'Discover AI-generated works. Reuse any prompt to start creating.',
    home_owner: 'Owner {value}',
    home_guest: 'Guest {value}',
    home_clone_prompt: 'Clone Prompt',
    home_favorite_case: 'Favorite Case',
    home_unfavorite_case: 'Remove Favorite',
    home_favorite_saved: 'Case saved to favorites',
    home_favorite_removed: 'Case removed from favorites',
    home_favorite_login_required: 'Sign in to favorite cases',
    home_generation_login_required: 'Register or sign in before generating images',
    home_prompt_copied: 'Prompt loaded and copied',
    home_mode: 'Mode',
    home_mode_edit: 'Edit',
    home_mode_generate: 'Generate',
    home_panel_expand: 'Expand generator',
    home_panel_collapse: 'Collapse generator',
    home_tab_general: 'Generate',
    home_tab_ecommerce: 'E-commerce',
    home_ecom_product_image: 'Product Image',
    home_ecom_product_name: 'Product Name',
    home_ecom_materials: 'Materials',
    home_ecom_selling_points: 'Selling Points',
    home_ecom_scenarios: 'Scenarios',
    home_ecom_platform: 'Platform',
    home_ecom_style: 'Visual Style',
    home_ecom_extra: 'Extra Requirements',
    home_ecom_upload_tip: 'Upload product image',
    home_ecom_missing_image: 'Upload a product image first',
    home_ecom_sent: 'E-commerce detail task dispatched',
    home_ecom_image_ready: 'Product image loaded',
    home_ecom_image_removed: 'Product image removed',
    ecom_reset_form: 'Reset form',
    ecom_form_reset: 'E-commerce form reset',
    ecom_tag: 'Commerce Studio',
    ecom_title: 'E-commerce Detail Design',
    ecom_subtitle: 'Upload a product image, generate a detail-page set, then keep editing each result as a project.',
    ecom_projects: 'Design Projects',
    ecom_empty: 'No e-commerce design projects yet.',
    ecom_open_project: 'Open Project',
    ecom_project_detail: 'Project Detail',
    ecom_back_projects: 'Back to Projects',
    ecom_reference_image: 'Reference Image',
    ecom_no_reference: 'No Reference',
    ecom_screen_index: 'Screen {value}',
    ecom_edit_this_image: 'Edit This Image',
    ecom_edit_references: 'Edit References',
    ecom_edit_reference_tip: 'The original product image and current result are used by default. Add extra references only for style, scene, or local details.',
    ecom_add_reference: 'Add Ref',
    ecom_form_restored: 'Project submission parameters restored',
    ecom_publish_material: 'AI Publish Copy',
    ecom_publish_hint: 'Generate independent copy from this product topic, selling points, and scenes for Xiaohongshu or social posts.',
    ecom_publish_title: 'Title',
    ecom_publish_body: 'Body',
    ecom_generate_publish: 'Generate Copy',
    ecom_regenerate_publish: 'Regenerate Copy',
    ecom_publish_empty: 'Click generate to create an independent title and body from the current project parameters.',
    ecom_publish_generated: 'Publish copy generated',
    ecom_copy_title: 'Copy Title',
    ecom_copy_body: 'Copy Body',
    ecom_copy_all: 'Copy All',
    ecom_publish_copied: 'Publish copy copied',
    ecom_generation_login_required: 'Register or sign in before generating e-commerce images',
    ecom_ai_designer: 'AI Product Designer',
    ecom_ai_designer_hint: 'When users only have product photos, analyze product traits, selling points, scenes, and suitable design directions before applying a plan.',
    ecom_analyze_product: 'Analyze Product',
    ecom_analyzing: 'Analyzing',
    ecom_analysis_ready: 'Product analysis completed',
    ecom_analysis_empty: 'Upload a product image and analyze it to get product traits plus 3 generation-ready design plans.',
    ecom_analysis_summary: 'Product Analysis',
    ecom_analysis_type: 'Product Type',
    ecom_analysis_appearance: 'Appearance',
    ecom_analysis_material: 'Visible Material',
    ecom_analysis_constraints: 'Consistency Rules',
    ecom_apply_plan: 'Apply Plan',
    ecom_plan_applied: 'Recommended plan applied',
    home_message_edit_sent: 'Edit request dispatched',
    home_message_generate_sent: 'Generation request dispatched',
    home_message_queued: 'Task submitted and queued',
    home_message_processing: 'Task running, please wait',
    home_message_saved: 'Result stored in archive',
    home_message_waiting: 'Awaiting input',
    home_message_loaded: 'Selected configuration loaded',
    home_placeholder: 'Enter your prompt here...',
    home_ref_image: 'Ref Image',
    reference_role: 'Role',
    reference_note: 'Note',
    reference_note_placeholder: 'What should this image guide?',
    reference_role_subject: 'Subject/Main',
    reference_role_front: 'Front',
    reference_role_side: 'Side',
    reference_role_back: 'Back',
    reference_role_material: 'Material Detail',
    reference_role_color: 'Color Reference',
    reference_role_structure: 'Structure',
    reference_role_scene: 'Scene Reference',
    reference_role_style: 'Style Reference',
    reference_role_layout: 'Layout Reference',
    reference_role_other: 'Other',
    home_execute: 'Execute',
    home_edit: 'Edit',
    home_generate: 'Generate',
    home_optimize_prompt: 'AI Optimize',
    home_optimizing_prompt: 'Optimizing',
    home_prompt_instruction: 'Edit request, e.g. change subject and keep composition',
    home_prompt_optimized: 'Prompt optimized',
    home_prompt_optimizer_empty: 'Enter a prompt first',
    home_ref_image_invalid: 'Drop PNG, JPG, or WebP images',
    home_size: 'Size',
    home_size_fast: 'Fast',
    home_aspect_ratio: 'Ratio',
    home_quality: 'Quality',
    home_image_count: 'Count',
    create_workspace_tag: 'Creation Workspace',
    create_workspace_title: 'Turn an idea into an executable generation task',
    create_workspace_desc: 'Describe the subject, scene, style, and use case. Drop in references when you need to preserve product details, materials, or composition.',
    create_active_tasks: '{count} tasks running',
    create_task_center_idle: 'Task center idle',
    create_mode_general_title: 'Image Generation',
    create_mode_general_sub: 'General image model',
    create_mode_ecommerce_title: 'Commerce Image',
    create_mode_ecommerce_sub: 'Product scene images',
    create_task_input_title: 'Task Input',
    create_reference_flow: '{count} reference images added. This will use the edit/reference generation flow.',
    create_text_flow: 'No reference images added. This will use text-to-image generation.',
    create_remove_reference: 'Remove reference image',
    create_reference_role_label: 'Reference image role',
    create_reference_note_label: 'Reference image note',
    create_reference_note_placeholder: 'e.g. use material texture',
    create_reference_upload_title: 'Drop or upload reference images',
    create_reference_upload_desc: 'Product shots, material details, and style references all work. Up to 8 images.',
    create_add_reference: 'Add reference image',
    create_prompt_placeholder_general: 'Describe subject, environment, composition, lighting, and style, e.g. mechanical flowers in a glass greenhouse, morning natural light, refined materials...',
    create_prompt_placeholder_ecommerce: 'Describe the product, selling points, and target scene, e.g. white running shoes, clean studio background, emphasize sole texture and lightweight motion...',
    create_prompt_required: 'Enter a prompt',
    create_prompt_before_optimize: 'Enter a prompt first',
    create_generate_image: 'Generate Image',
    create_example_general_1: 'A futuristic city night poster, rain-soaked streets reflecting neon, cinematic lighting, 16:9',
    create_example_general_2: 'White mechanical flowers inside a glass greenhouse, morning natural light, refined materials, clean composition',
    create_example_general_3: 'Retro sci-fi magazine cover, an orange probe ship crossing Saturn rings, grainy film texture',
    create_example_ecommerce_1: 'Black smart watch on rock and cold-lit water, emphasize metal bezel and sporty waterproof feel',
    create_example_ecommerce_2: 'White running shoe on a clean studio background, slight levitation, emphasize sole texture and breathable mesh',
    create_example_ecommerce_3: 'Skincare serum bottle on a warm bathroom counter, water droplets and soft morning light, premium commerce hero image',
    create_workflow_general_1: 'Enter scene and style',
    create_workflow_general_2: 'Optionally add references',
    create_workflow_general_3: 'Continue editing in the workspace',
    create_workflow_ecommerce_1: 'Upload product or style references',
    create_workflow_ecommerce_2: 'Describe selling points and usage scene',
    create_workflow_ecommerce_3: 'Output hero and scene-ready product images',
    create_output_title: 'Output Preview',
    create_output_reference_mode: 'Reference Generation',
    create_output_text_mode: 'Text Generation',
    create_output_size: 'Size',
    create_output_count_value: '{count} images',
    create_output_desc: 'After submission, the task opens in its own workspace where you can view results, keep editing, and return from history.',
    create_recent_tasks_title: 'Recent Tasks',
    create_view_all_tasks: 'View All',
    create_recent_tasks_empty: 'No tasks yet. Once you generate, recent running and completed tasks will appear here.',
    create_task_status_queued: 'Queued',
    create_task_status_running: 'Running',
    create_task_status_succeeded: 'Completed',
    create_task_status_failed: 'Failed',
    home_loading_feed: 'Loading prompt cases...',
    home_loading_more: 'Loading more cases...',
    home_load_more: 'Load More Cases',
    home_all_loaded: 'All cases loaded',
    home_empty_feed: 'No cases available yet.',
    home_case_search: 'Search case titles, prompts, or authors',
    home_case_search_keyword: 'Keyword',
    home_case_search_ai: 'AI Search',
    home_case_ai_searching: 'AI searching',
    home_case_ai_query: 'AI query: {value}',
    home_case_clear_search: 'Clear search',
    home_case_total: '{total} cases',
    home_case_search_results: '{total} results',
    home_back_to_top: 'Back to top',
    history_tag: 'History',
    history_title: 'History',
    history_subtitle: 'Access and manage previously synthesized visual records.',
    history_search: 'Search prompts...',
    history_apply_filter: 'Apply history filter',
    history_failed: 'Generation failed',
    history_download: 'Download',
    history_download_zip: 'Download ZIP',
    history_delete: 'Delete',
    history_preview: 'Preview',
    history_regenerate: 'Re-Generate',
    history_publish_case: 'Publish Case',
    history_unpublish_case: 'Unpublish',
    history_published: 'Published',
    history_load_more: 'Load More',
    history_loading: 'Syncing history',
    history_empty_title: 'No generation history yet',
    history_empty_desc: 'Create your first image and completed results will land here.',
    history_search_empty_title: 'No matching history',
    history_search_empty_desc: 'Try another prompt keyword or clear search to see everything.',
    history_login_title: 'Sign in to view history',
    history_login_desc: 'Sign in to sync generation history, continue editing, and regenerate work.',
    history_error_title: 'History failed to load',
    history_error_desc: 'The network or upstream service did not return data. Try again in a moment.',
    history_clear_search: 'Clear search',
    history_create_action: 'Create',
    history_retry: 'Retry',
    favorites_tag: 'Favorite Cases',
    favorites_title: 'Favorites',
    favorites_subtitle: 'Review saved public cases and reuse their prompts quickly.',
    favorites_search: 'Search favorite cases...',
    favorites_search_action: 'Search',
    favorites_loading: 'Loading favorites...',
    favorites_empty: 'No favorite cases yet.',
    favorites_empty_title: 'No favorite cases yet',
    favorites_empty_desc: 'Save cases from the inspiration feed and they will collect here.',
    favorites_search_empty_title: 'No matching favorites',
    favorites_search_empty_desc: 'Try a shorter keyword or clear search to return to all favorites.',
    favorites_error_title: 'Favorites failed to load',
    favorites_error_desc: 'The favorites list is temporarily unavailable. Please retry.',
    favorites_all_loaded: 'All favorites loaded',
    favorites_login_required: 'Favorites are available after sign-in.',
    favorites_login_title: 'Sign in to manage favorites',
    favorites_login_desc: 'Favorites are attached to your AetherGenix account and sync across devices.',
    favorites_explore_action: 'Explore',
    account_tag: 'Account',
    account_title: 'Account',
    account_identity: 'Identity',
    account_owner: 'Owner',
    account_registered: 'Registered User',
    account_guest: 'Guest Session',
    account_user: 'Display Name',
    account_sub2api_username: 'AetherGenix Username',
    account_email: 'Email',
    account_model: 'Model',
    account_api_key: 'Credit Access',
    account_api_managed: 'Account auto-bound',
    account_api_override: 'Account credits',
    account_api_manual: 'Guest credits',
    account_api_missing: 'Missing',
    account_balance: 'Available Credits',
    account_history: 'History',
    account_succeeded: '{value} succeeded',
    account_edits: 'Edits',
    account_last: 'Last: {value}',
    account_sync_hint: 'Sign in to sync credits and generation history',
    account_balance_synced: 'Available credits synced',
    account_balance_syncing: 'Available credits are syncing. Refresh again later.',
    account_balance_pending: 'Available credits are not synced yet. Refresh again later.',
    account_recent_generation: 'Recent Generation',
    account_area_title: 'My Account',
    account_current_identity: 'Current Identity',
    account_logged_in_identity: 'Signed in to AetherGenix',
    account_guest_identity: 'Guest experience',
    account_balance_unsynced: 'Not synced',
    account_generation_records: 'Generation Records',
    account_generation_record_value: '{total} generations, {edits} edits',
    account_refresh: 'Refresh Account',
    account_sync_error_desc: 'Account details did not sync just now. Credits and recharge status should recover after a later refresh.',
    account_recharge_action: 'Open Recharge Page',
    account_login_or_register: 'Sign in / Register',
    recharge_tag: 'Recharge',
    recharge_title: 'Available Credits',
    recharge_desc: 'After recharging, return here and refresh your balance.',
    recharge_open_external: 'Open Recharge Page',
    recharge_open_external_note: 'Opens in a new page. Return here after recharging and refresh your balance.',
    recharge_iframe_hint: 'After recharging, return to AetherGenix and refresh your balance.',
    recharge_login_required: 'Sign in to view credits',
    recharge_login_desc: 'Sign in to view your balance and open the recharge page.',
    recharge_loading: 'Loading recharge channel',
    recharge_current_balance: 'Current Balance',
    recharge_refresh: 'Refresh Balance',
    recharge_refreshing: 'Refreshing',
    recharge_external_desc: 'Your balance syncs automatically. Open the recharge page when you need more credits.',
    recharge_external_missing: 'Recharge entry is unavailable. Contact the site owner.',
    recharge_balance_syncing: 'Syncing balance',
    recharge_balance_updated: 'Balance updated',
    recharge_balance_pending: 'Balance not synced yet',
    recharge_balance_sync_failed: 'Balance could not sync',
    recharge_balance_retry: 'Retry',
    config_profile: 'Owner Profile',
    config_mode: 'Mode',
    config_mode_user: 'AetherGenix User',
    config_mode_guest: 'Guest',
    config_balance: 'Balance: {value}',
    config_guest_tip: 'You are using a guest experience. Sign in or register to sync credits and generation history.',
    config_sign_in: 'Sign In',
    config_register: 'Register',
    config_title: 'Settings',
    config_session_user: 'AetherGenix Account Session',
    config_session_guest: 'Guest Session',
    config_user_desc: 'This config is attached to the signed-in AetherGenix account. Account credits are selected automatically, with a backup access key available when needed.',
    config_guest_desc: 'Guest mode keeps data isolated by guest cookie and is best for temporary trials. Sign in to sync credits and generation history.',
    config_cases: 'Prompt Case Source',
    config_cases_summary: '{total} cases synced · last {time}',
    config_cases_sources: '{value} sources',
    config_sync_cases: 'Sync Cases',
    config_save_case_sources: 'Save Sources',
    config_user_name: 'User Name',
    config_model: 'Model',
    config_size: 'Size',
    config_quality: 'Quality',
    config_api_key: 'Backup Access Key',
    config_saved_key: 'Saved key: {value}',
    config_key_managed: 'managed',
    config_key_override: 'manual override',
    config_key_manual: 'manual',
    config_restore_key: 'Restore managed key',
    config_test: 'Test Link',
    config_save: 'Save Config',
    config_usage_log: 'Usage Log',
    config_usage_log_empty: 'No usage log yet',
    config_usage_actual: 'Actual',
    config_usage_estimated: 'Estimated',
    config_status_saved: 'Config saved',
    config_status_connected: 'Connected: {value}',
    config_status_synced: 'Synced {value} cases',
    config_status_restored: 'Restored managed key',
    config_status_site_saved: 'Site settings saved',
    config_site_title: 'Interface & Announcement',
    config_site_desc: 'Language selection is stored in the current browser. When an admin saves, it also becomes the site default along with the announcement.',
    config_default_user_name: 'AetherGenix User',
    config_account_settings: 'Account Settings',
    config_guest_tip_plain: 'You are using a guest experience. Sign in or register to sync credits and generation history.',
    config_user_desc_plain: 'You are signed in to AetherGenix. Credits and generation history sync with your account.',
    config_guest_desc_plain: 'Guest data is saved only in this browser. Sign in to sync credits and history across devices.',
    config_account_profile: 'Account Profile',
    config_display_name: 'Display Name',
    config_email: 'Email',
    config_email_after_login: 'Shown after sign-in',
    config_account_status: 'Account Status',
    config_status_signed_in: 'Signed in and syncing account data',
    config_status_guest: 'Guest experience, stored only in this browser',
    config_balance_status: 'Credit Status',
    config_balance_status_desc: 'Image generation automatically uses your account credits. Use the shared recharge entry when you need more credits.',
    config_usage_summary: 'Usage Summary',
    config_usage_total: 'Creations',
    config_usage_succeeded: 'Succeeded',
    config_usage_last: 'Latest Creation',
    config_site_desc_user: 'Choose your preferred interface language. Site announcements will remind you when updated, and you can reopen them here.',
    config_announcement_pref: 'Announcement Reminder',
    config_announcement_disabled: 'No announcement is enabled',
    config_announcement_empty_enabled: 'Site announcements are enabled. You will be reminded when content updates.',
    config_announcement_placeholder: 'New site notices will appear here.',
    config_view_announcement: 'View Announcement',
    login_access: 'Access',
    login_title: 'Sign In',
    login_title_2fa: 'Two-Factor Check',
    login_desc: 'Use your AetherGenix account. Credits and generation history are synced after sign-in.',
    login_desc_2fa: 'Enter the 6-digit code for {value}.',
    login_email: 'Email',
    login_password: 'Password',
    login_totp: 'TOTP Code',
    login_submit: 'Sign In',
    login_submit_2fa: 'Verify 2FA',
    login_new: 'New account?',
    register_access: 'Enrollment',
    register_title: 'Create Account',
    register_desc: 'Create an AetherGenix account to generate with the same credits and sync generation history.',
    register_disabled: 'New account registration is not open right now.',
    register_email: 'Email',
    register_password: 'Password',
    register_verify_code: 'Verify Code',
    register_send_code: 'Send Code',
    register_promo: 'Promo Code',
    register_invitation: 'Invitation Code',
    register_submit: 'Register',
    register_exists: 'Already registered?',
    lang_label: 'Language',
    lang_zh: '中文',
    lang_en: 'English',
    site_announcement: 'Announcement',
    site_announcement_enabled: 'Enable popup announcement',
    site_announcement_title: 'Announcement title',
    site_announcement_body: 'Announcement body',
    site_upstream: 'Sub2API Integration',
    site_upstream_hint: 'Leave blank to use environment variables. After saving, generation, auth, balance, and usage logs use the new Sub2API instance.',
    site_provider_base_url: 'Sub2API /v1 proxy URL',
    site_auth_base_url: 'Sub2API auth management URL',
    site_recharge_url: 'Sub2API recharge page URL',
    site_upstream_effective: 'Active: {value}',
    site_admin_token: 'Sub2API Admin API Key',
    site_admin_jwt: 'Sub2API Admin JWT',
    site_admin_token_hint: 'Used to grant new-user trial balance. Leave blank to keep the saved value; paste a new value to replace it.',
    site_admin_token_saved: 'Current: {value}',
    site_trial_balance_usd: 'New-user trial balance',
    site_trial_balance_effective: 'Active grant: ${value}',
    site_inspiration_sources: 'Case Sources',
    site_inspiration_sources_body: 'Case source URLs, one per line. GitHub repo URLs and raw README URLs are both supported.',
    site_announcement_save: 'Save Announcement',
    site_settings_save: 'Save Site Settings',
    site_admin_only: 'Only admins can edit site settings.',
    announcement_empty: 'No announcement available.',
    modal_close: 'Close',
    modal_preview: 'Image Preview',
    modal_open_image: 'Open Original',
    modal_download: 'Download',
    modal_previous: 'Previous',
    modal_next: 'Next',
    image_load_failed: 'Image failed to load',
    image_retry: 'Retry',
    prompt_editor_title: 'Prompt Editor',
    prompt_editor_expand: 'Expand Editor',
    prompt_editor_collapse: 'Collapse',
    prompt_editor_copy: 'Copy',
    prompt_editor_clear: 'Clear',
    tasks_title: 'Task Center',
    tasks_subtitle: 'Submitted generate and edit jobs continue here in the background.',
    tasks_empty: 'No tasks yet.',
    tasks_empty_title: 'No background tasks yet',
    tasks_empty_desc: 'Submit a generate or edit job from Create and progress will appear here.',
    tasks_filter_empty_title: 'No tasks in this filter',
    tasks_filter_empty_desc: 'Return to all tasks or start a new creation.',
    tasks_clear_filter: 'View all',
    tasks_create_action: 'Create',
    tasks_open_history: 'Open History',
    tasks_active: '{value} active',
    tasks_idle: 'Idle',
    tasks_filter_all: 'All',
    tasks_filter_active: 'Active',
    tasks_filter_succeeded: 'Done',
    tasks_filter_failed: 'Failed',
    tasks_status_queued: 'Queued',
    tasks_status_running: 'Running',
    tasks_status_succeeded: 'Done',
    tasks_status_failed: 'Failed',
    tasks_toast_succeeded: 'Task Complete',
    tasks_toast_failed: 'Task Failed',
    toast_success: 'Success',
    toast_error: 'Error',
    toast_info: 'Notice',
  },
} as const;

const SiteContext = createContext<SiteContextValue | null>(null);

export function SiteProvider({ children }: { children: ReactNode }) {
  const { viewer } = useAuth();
  const location = useLocation();
  const [siteSettings, setSiteSettings] = useState<SiteSettings | null>(null);
  const [locale, setLocaleState] = useState<Locale>('zh-CN');
  const [announcementOpen, setAnnouncementOpen] = useState(false);
  const suppressAutoAnnouncement =
    location.pathname === '/account' ||
    location.pathname.startsWith('/account/') ||
    location.pathname === '/recharge' ||
    location.pathname.startsWith('/recharge/');

  async function refreshSiteSettings() {
    try {
      const next = await getSiteSettings();
      setSiteSettings(next);
      const storedLocale = window.localStorage.getItem(LOCALE_STORAGE_KEY) as Locale | null;
      if (storedLocale === 'zh-CN' || storedLocale === 'en-US') {
        setLocaleState(storedLocale);
      } else if (next.default_locale === 'en-US' || next.default_locale === 'zh-CN') {
        setLocaleState(next.default_locale);
      } else {
        setLocaleState('zh-CN');
      }
    } catch {
      setSiteSettings(null);
      setLocaleState('zh-CN');
    }
  }

  useEffect(() => {
    refreshSiteSettings().catch(() => undefined);
  }, [viewer?.owner_id]);

  useEffect(() => {
    if (suppressAutoAnnouncement) {
      return;
    }
    if (!siteSettings?.announcement.enabled || !siteSettings.announcement.updated_at) {
      return;
    }
    const seenAt = window.localStorage.getItem(ANNOUNCEMENT_SEEN_KEY);
    if (seenAt !== siteSettings.announcement.updated_at) {
      setAnnouncementOpen(true);
    }
  }, [siteSettings?.announcement.enabled, siteSettings?.announcement.updated_at, suppressAutoAnnouncement]);

  function setLocale(nextLocale: Locale) {
    setLocaleState(nextLocale);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, nextLocale);
  }

  function openAnnouncement() {
    setAnnouncementOpen(true);
  }

  function closeAnnouncement() {
    setAnnouncementOpen(false);
    const updatedAt = siteSettings?.announcement.updated_at;
    if (updatedAt) {
      window.localStorage.setItem(ANNOUNCEMENT_SEEN_KEY, updatedAt);
    }
  }

  const value = useMemo<SiteContextValue>(() => ({
    locale,
    setLocale,
    t: (key, vars) => {
      const template = translations[locale][key] || translations['zh-CN'][key] || key;
      if (!vars) return template;
      return Object.entries(vars).reduce((result, [name, value]) => result.replace(`{${name}}`, String(value)), template);
    },
    siteSettings,
    refreshSiteSettings,
    announcementOpen,
    openAnnouncement,
    closeAnnouncement,
  }), [locale, siteSettings, announcementOpen]);

  return <SiteContext.Provider value={value}>{children}</SiteContext.Provider>;
}

export function useSite() {
  const context = useContext(SiteContext);
  if (!context) {
    throw new Error('useSite must be used inside SiteProvider');
  }
  return context;
}
